import os

csv_content = """prod_141,PRODUCTOS MH,TRATAMIENTO SISTEMA NERVIOSO D4 MH,GELSEMIUM D4 MH: Gotas x 30 ml|ZINCUM MET MH: Gotas x 30 ml|MELISSA D4 MH: Gotas x 30 ml,Abordaje integral del miedo; la ansiedad; el estrés y el insomnio.^El Gelsemium nos ayuda a manejar la ansiedad; el Zincum patologías como depresión; miedos entre otras y la Melissa al ser un sedante natural; nos ayuda a conciliar el sueño; manejar el estrés.,,Kit,activo
prod_142,PRODUCTOS MH,TRATAMIENTO SOBREPESO D4 MH,RUMEX D4 MH: Tabletas por 90|Fucus D4 MH: Cápsulas por 30,Tratamiento para reducción de peso.^El Rumex se encarga de la detoxificación del organismo y el fucus trabaja sobre el tejido adiposo; el metabolismo y la ansiedad.,1 cápsula de fucus en ayunas diariamente y una antes del almuerzo; 1 tableta de rumex 3 veces al día.,Kit,activo
prod_143,PRODUCTOS MH,URANIUM D4 MH,Glycine max TM; Acidum citricum D9; Acidum fumaricum D9; Acidum phosphoricum D12; Arsenicum album D12; Ruta D6; Cerium oxalicum D9; Cobaltum D4; Cromiun D4; Equisetum D12; Helonias D3; Juglans D12; L-Cysteinum TM7; Leptandra D6; Lycopodium D30; Magnesium D4; Manganum D4; Phaseolus vulgaris D12; Secale cornutum D9; Sulphur D12; Syzygium D3; Uranium nitricum D9; Zincum met D4.,Diabetes; como coadyuvante.,1 cápsula 3 veces al día,Frasco por 90 cápsulas,activo
prod_144,PRODUCTOS MH,URTICA D4 MH GEL O CREMA,Aloe D3; Equisetum D3; Árnica D3; Caléndula D3; Urtica urens D3.,Afecciones de la piel en general; pañalitis; dermatitis de contacto.,,Tubo por 120g.,activo
prod_145,PRODUCTOS MH,VACCINIUM D4 MH,Botulinum 30CH; Vaccinium 30CH; E-Coli 30CH; Pneumococcinum 30CH; Proteus 30CH; Pseudomonas 30CH; Salmonella 30CH; Scarlatinum 30CH; Staphylococcinum 30CH; Streptococcinum 30CH; Tuberculinum 30CH.,Infecciones bacterianas; internas o externas; sistema inmune débil; o como preventivo de infiltración bacterial; Generadores de inmunidad activa (o pasiva) contra las enfermedades infecciosas. Gracias a las altas diluciones; carece de efectos secundarios.,,Gotas x 30 ml; Tabletas x 90; Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_146,PRODUCTOS MH,VIBURNUM D4 MH,Alumina D8; Cinnamomum D4-D6; Lilium D4-D6; Viburnum D12; Ustilago D8; Viburnium D6.,Leucorrea; fertilidad femenina; fibroma uterino; regulador hormonal.,,Gotas x 30 ml; Tabletas x 90; Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_147,PRODUCTOS MH,VINCETOXICUM D4 MH,Coxsackie 30CH; Diphterinum 30CH; Epstein Barr 30CH; Herpes simplex 30CH; Herpes zoster 30CH; Influenzinum 30CH; Morbillinum 30CH; Poliomielytum 30CH; V-Grippe 30CH; Caryophyllus aromaticus 30CH; Euphrasia D6; Vincetoxicum D6.,Enfermedades virales de la piel y de las mucosas; sarampión; mononucleosis; herpes; gripe viral; etc. Fortalecimiento de la defensa viral natural estimulándose el sistema inmunizante.,,Gotas x 30 ml; Tabletas x 90; Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_148,PRODUCTOS MH,VIPERA D4 MH,Árnica D4-D6-D30; Calcium sulphuricum D8-D12; Carbo vegetabilis D12-D30-D200; Fluoricum acidum D6-D12-D30; Ginkgo biloba D4-D6; Hamamelis D4-D6-D12; Hydrastis D4-D6-D30; Nitricum acidum D6-D8-D30; Secale cornutum D4; Vipera D8-D12-D30.,Gangrena; arteriosclerosis; tromboflebitis; destrucción del tejido; úlceras varicosas; enfermedad de Reynaud.,,Gotas x 30 ml; Tabletas x 90; Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_149,PRODUCTOS MH,VISCUM D4 MH,Berberis vulg D6-D12; Carbo vegetabilis D30-D200; Colchicum D6-D12-D30; Echinacea angustifolia D4-D12-D30; Galium aparine D6-D12-D30; Lacticum acidum D12; Phosphorus D12-D30; Sulphur D30; Urtica urens D3-D6; Viscum álbum D6-D12-D30-D200.,Precancerosis; patologías degenerativas; estimulante inmunológico; alergias; neoplasias.,,Gotas x 30 ml; Tabletas x 90; Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_150,PRODUCTOS MH,VITEX D3 MH,Vitamina D3; Vitamina K.,Deficiencia de vitamina D,,Gotero de pera x 30 ml.,activo"""

# Limpieza de artefactos PDF
csv_content = csv_content.replace('\u001b', 'f').replace('\u001e', 'fl').replace('\u001f', 'fi')

target_csv = r'c:\Users\Alfredo Pabón\Documents\Proyectos antigravity\mundo_homeopatico_v2\carpeta_temporal_tablas\vademecum_maestro.csv'

with open(target_csv, 'a', encoding='utf-8', newline='') as f:
    f.write('\n' + csv_content.strip())

print('Bloque 15 (141-150) anexado correctamente.')
