import os

csv_content = """prod_091,PRODUCTOS MH,MARRUBIUM D4 MH,DPT 200CH-1000CH; Luesinum 200CH; Marrubium 200CH; Medorrhinum 200CH-1000CH; Tuberculinum 200CH.,Patologías crónicodegenerativas; discracias; nosode antimiasmático.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_092,PRODUCTOS MH,MEDICAGO D4 MH,Aranea diadema D30; Arsenum iodat. D8; Ceanothus americ. D6; Chelidonium D6; China D6; Cuprum D8; Gentiana D3; Ferrum phos D8; Ferrum met D8; Medicago sativa D3; Silícea D8.,Anemia; falta de apetito de los niños; cansancio en la escuela; fatiga; produce una acción compleja que estimula la función del hígado así como de la médula ósea.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_093,PRODUCTOS MH,MELISSA D4 MH,Acido picricum D8; Avena sativa D4; Chamomilla D3; Crataegus D3; Datura stramonium D6; Hypericum perf D3 D6; Kalium bromatum D8; Kalium Phosphoricum D8; Melissa D3-D6-D12; Passiflora inc D3-D6; Ignatia amara D3-D6; Valeriana officinalis D3-D6.,Insomnio.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_094,PRODUCTOS MH,MERCURIUS D4 MH,Antimonium tartaricum D8; Argentum nitricum D6; Condurango D3; Hydrastis D4; Kalium Bichromicum D8; Mercurius D6; Mucosa D8; Nitricum acidum D6; Nux vómica D12.,Estimulación de las defensas propias del organismo en caso de afección de las mucosas (Digestivas - Respiratorias).,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_095,PRODUCTOS MH,MEZEREUM D4 MH,Antimonium crudum D12; Calcium fluoricom D8; Caléndula D3; Chelidonium D6-D30; Crotalus D30; Echinacea D4; Graphites D8-D12; Lachesis D8; Mezereum D6-D12-D30; Sulphur D12-D30.,Alergias; dermatosis; piodermitis; eccema; herpes zoster; prurito; eccemas vesiculares; psoriasis.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_096,PRODUCTOS MH,NUX VÓMICA D4 MH,Abies D6; Aloe D3-D6; Alumina D8-D12-D30; Colocynthis D12-D30; Lycopodium D6-D12; Nux vómica D6-D12-D30; Cascara sagrada D3-D6; Robina D6-D12; Veratrum D8-D12.,Estreñimiento espasmódico; afecciones hepáticas; agotamiento nervioso; meteorismo; alcoholismo; enfermedades digestivas.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_097,PRODUCTOS MH,ORIGANUM D4 MH,Glycine max TM; L-Arginina TM; Maca TM; NU BAO TM; ORIGANUM (MEJORANA) TM-D4-D6; Zincum metalicum D4.,Este es un medicamento que aumenta la energía sexual de las mujeres y la restaura la función hormonal; el mantenimiento de la vitalidad óptima de la mujer y la apariencia de retrasar el envejecimiento prematuro en las mujeres.,1 cápsula 3 veces al día,Frasco por 90 cápsulas,activo
prod_098,PRODUCTOS MH,PASSIFLORA D4 MH,Avena sativa D6-D12; Kalium Bromatum D8-Melissa D6-D12; Opium D30; Passiflora D6-D30-D200; Phosphoricum acidum D6-D30; Valeriana D6-D12-D30; Zincum D12-D30.,Estrés; nerviosismo; insomnio; intranquilidad; agotamiento físico y mental.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_099,PRODUCTOS MH,PETROLEUM D4 MH,Agaricus D6; Ambra grisea D12; Argentum nitric. D30; Cocculus D30; Conium D30; Curarum D12; Gelsemium D6; Petroleum D6-D12-D30; Stramonium D12; Tabacum D4; Theridion curassavic D30.,Vértigo de diferentes causas; vértigo de Menier; trastornos cerebrales de la circulación a consecuencia de esclerosis cerebral; trastornos vegetativos de la circulación.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_100,PRODUCTOS MH,PHOSPHORICUM ACIDUM D4 MH,Atp; Vitaminas; Phosphoricum acidum D12.,Especialmente indicado en enfermedades degenerativas; miopatías de origen metabólico; coadyuvante en el tratamiento de degeneraciones musculares; actúa como reconstituyente; por sus componentes individuales Phosphoricum acidumh ATP se útiliza también para promover la recuperación de todas las funciones de la célula.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo"""

# Limpieza de artefactos PDF
csv_content = csv_content.replace('\u001b', 'f').replace('\u001e', 'fl').replace('\u001f', 'fi')

target_csv = r'c:\Users\Alfredo Pabón\Documents\Proyectos antigravity\mundo_homeopatico_v2\carpeta_temporal_tablas\vademecum_maestro.csv'

with open(target_csv, 'a', encoding='utf-8', newline='') as f:
    f.write('\n' + csv_content.strip())

print('Bloque 10 (91-100) anexado correctamente.')
