import os

csv_content = """prod_061,PRODUCTOS MH,GENTIANA D4 MH,Avena sativa D3; Condurango D3-D6; Gentiana D3; Ginseng D3; Marrubium vulgare D3; Menyanthes D30; Taraxacum D30.,Anorexia; inapetencia; dispepsia.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_062,PRODUCTOS MH,GINKGO BILOBA D4 MH,Fucus vesiculosus D4; Ginkgo biloba D3; Vitamina B12 D6; Zincum metallicum D8.,Poca oxigenación; debilidad; fatiga. Para uso deportivo usar con algún programa de entrenamiento.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_063,PRODUCTOS MH,GLONOINUM D4 MH,Aconitum D12; Aurum met D8; Árnica D4-D6; Baryta D8; Cholesterolum D8; Fluoricum acidum D4-D6; Glonoinum D6; Iodum D8; Kali iodatum D8; Plumbum D8; Strophantus D6.,Arteriosclerosis. Circulación arterial.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_064,PRODUCTOS MH,GRAPHITES D4 MH,Cutis D8-D12; Galium D6; Graphites D6; Hepar D10; Ledum D6; Passiflora D30; Petroleum D6; Selenium D30; Staphisagria D6; Sulphur D12; Urtica D6.,Enfermedades de piel y mucosas; estimulación de los sistemas de defensa en casi de dermatitis; dermatosis; alergia; acné vulgar; esclerodermia; dermatitis atópica; micosis interdigital; alopecia.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_065,PRODUCTOS MH,GRAPHITES D4 MH CREMA O GEL,Caléndula D3; Echinacea D3; Graphites D3; Silícea D3; Sulphur D3; Urtica D3.,Diseñada especialmente para tratar las úlceras de pie diabético; Indicada también en úlceras varicosas y grietas en la piel.,,Tubo 120g.,activo
prod_066,PRODUCTOS MH,GRAPHITES D4 MH UNGÜENTO (BÁLSAMO),Graphites D6; Caléndula D3; Silicea D3; Aloe D1; Cera de abejas; Cera carnauba; Aceite de oliva; Lanolina; Urtica D3; Colágeno.,Coavyudante en el tratamiento de Psoriasis; piel reseca; Hiperqueratosis; se puede utilizar en veterinaria para humectar las huellas de los animales (pulpejo) y codos.,,Pote 40g.,activo
prod_067,PRODUCTOS MH,HAMAMELIS D4 MH,Aesculus D6; Árnica D6-D12; Belladona D4; Calcium fluoratum D8; Carduus marianus D6-D12; Fluoricum acidum D6-D12; Hamamelis D3-D6-D12; Mezereum D6; Pulsatilla D6-D30; Secale cornutum D12.,Várices; complejo sintomático varicoso; estasis venosa; tromboflebitis; úlcera varicosa; traumatismos de todo tipo; golpes; procesos inflamatorios; patologías circulatorias.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_068,PRODUCTOS MH,HAMAMELIS D4 MH CREMA O GEL,Hamamelis D3; Árnica D3; Aesculus D3; Ruscus aculeatus D3; Calcium Fluoratum D3.,Várices; flebitis; inflamación; edema en piernas; hematomas.,,Gel 120g. Crema 120g,activo
prod_069,PRODUCTOS MH,HARPAGOPHYTUM D4 MH,Harpagophytum procumbens,Excelente acción anti inflamatoria; se recomienda en caso de dolores articulares; reumáticas; artrósicos y artríticos; reduce notablemente la sensación de dolor y mejora el movimiento sin efectos adversos.,,Frasco por 90 cápsulas.,activo
prod_070,PRODUCTOS MH,HEDERA HELIX D4 MH GEL,Equisetum Arvense D3; Centella asiática D3; Ginkgo Biloba D3; Aesculus D3; Fucus Vesiculosis D3; Camelia Sinensis D3; Hedera Helix D3.,Gel tonificante; reafirmante.,Aplicar en la mañana y en la tarde con masaje circular ascendente.,Pote por 120gr.,activo"""

target_csv = r'c:\Users\Alfredo Pabón\Documents\Proyectos antigravity\mundo_homeopatico_v2\carpeta_temporal_tablas\vademecum_maestro.csv'

with open(target_csv, 'a', encoding='utf-8', newline='') as f:
    f.write('\n' + csv_content.strip())

print('Bloque 7 (61-70) anexado correctamente.')
