import os

csv_content = """prod_081,PRODUCTOS MH,KALIUM BICH D4 MH Sistema respiratorio,Aconitum D4; Allium cepa D6; Argentum nitricum D6; Belladona D6; Bryonia alba D6; Coccus D6; Drosera D3; Euphatorium perfoliatum D3; Euphorbium D4-D6; Euphrasia D6; Ferrum phos. D8; Hydrastis D4 -D6-D12; Ipeca D3; Kalium bichromicum D8; Lemna minor D3-D6-D12; Lobelia D6- D12; Luffa D6-D12; Phosphorus D12; Rumex crispus D4; Sabadilla D6; Sambucus nigra D3-D6; Spongia D8.,Congestión de vías respiratorias; enfermedades de la pleura y el pulmón; diferentes tipos de tos (tos espasmódica nocturna; tos laríngea; tos seca; tos ferina); rinitis; sinusitis; traqueitis; laringitis entre otras.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_082,PRODUCTOS MH,KALIUM BROMATUM D4 MH,Ascorbicum acidum; Ammonium bromat D12; Bromum D12; Carbo vegetabilis D12-D30; Hepar sulf. D30; Juglans D30; Kalium bromat. D8-D12; Ledum D30; Natrium chlorat. D200; Sulphur D12. Viola tric. D12.,Acné vulgar; acné pustuloso; acné rosácea; piel seca; seborrea.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_083,PRODUCTOS MH,KALMIA D4 MH,Árnica D3-D6; Causticum D4-D6; Cuprum D8; Dulcamara D6; Fórmica rufa D6-D12; Kalmia D4-D6-D12; Rhus toxicodendron D4-D6; Symphytum D4-D6.,Artritis; reumatismo muscular; neuritis; calambres; gonartrosis; poliartrosis; procesos inflamatorios y degenerativos asociados con el aparato locomotor y ligamentos; periartritis escapohumeral.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_084,PRODUCTOS MH,KALMIA GEL D4 MH,Harpagophytum D1; Cannabis D1; Kalmia D2; Arnica D2; Fórmica rufa D2; Rhus tox D2; Symphytum D2; Dulcamara D2; Apis D3; Magnesia Phosphorica D8.,Artrítis; Reumatismo Muscular; Neuritis; Calambres; Poliartrosis; Procesos inflamatorios degenerativos,,Gel 120g,activo
prod_085,PRODUCTOS MH,LEPTANDRA D4 MH,Apis mellifica D5; Carduus marianus D6 D12; Colocynthis D6; Leptandra D6; Lycopodium D6; Momordica balsamina D3; Phosphorus D6; Rosmarinus D6.,Pancreatitis; disfunciones del páncreas.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_086,PRODUCTOS MH,LILIUM D4 MH,Angélica sinensis D3-D6; Apis mell D4-D6; Calcium fluoricum D12; Hamamelis vir D4-D6; Lilium tigrinum D3-D6.,Disfunciones ováricas.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_087,PRODUCTOS MH,LILIUM D4 MH - ÓVULOS VAGINALES,Lilium tigrinum D3; caléndula D3; echinacea D3; hydrastis D6; plata coloidal 25ppm; equisetum D6; hamamelis D6; pulsatilla D6; juglans D3; thuja D6 D12.,Dismenorreas; quistes; tumores; miomas; antiséptico; antiinflamatorio; resequedad vaginal; candidiasis; leucorrea; vaginitis.,Aplicar un óvulo intravaginal en la noche antes de acostarse.,Blister x 12 óvulos.,activo
prod_088,PRODUCTOS MH,LUFFA D4 MH,Allium cepa D12; Apis D4; Echinacea D3-D4; Euphatorium perfoliatum D3; Hydrastis canadensis D3; Kalium bichromicum D8; Lachesis D8; Lobelia D6-D12; Luffa D6-; D12; Phosphorus D12; Pulsatilla D4; Sabadilla D12; Sulphur iodatum D8; Thuja D6.,Rinitis; sinusitis.,Una aplicación en cada fosa nasal dos o tres veces al día o según criterio médico.,Spray nasal x 30 ml.,activo
prod_089,PRODUCTOS MH,MAGNESIA PHOSPHORICA D4 MH,Amonium muriaticum D8; Árnica D4; Arsenicum album D6; Bryonia D3-D6-D12; Colocynthis D12; Cuprum met D8; Gnaphallium D6-D12; Kallium iodatum D8; Magnesia carbonica D8; Magnesia phosphoric D8; Stilingia D8; Sulphur D30.,Ciática; calambres; neuralgias; mialgias; reumatismo; dolor lumbar.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_090,PRODUCTOS MH,MANGANUM D4 MH,Este medicamento se elabora en una base de vitaminas ; oligoelementos y aminoácidos.|Glycine max TM; Ácido Nicotínico TM; Avena Sativa D4-D6-D12-D30-D100; Baryta D12; Coenzime Q10 D6; Colina D6-D12; Galium D6-D12-D30; Lapis albus D6; Manganum D6; Magnesium D6; Phosphoricum acidum D6; Piroxina (Vitamina B6)TM; Tiamina TM; Zincum Metalicum D6; D30.,Modulador del tiempo biológico de las células; protector del sistema nervioso central; antioxidante y estimulador del sistema inmunitario; inductor del sueño; regulador del sistema hormonal; coadyuvante el tratamiento de la hipertensión arterial.,1 cápsula 3 veces al día,Frasco por 90 cápsulas,activo"""

# Limpieza de artefactos PDF
csv_content = csv_content.replace('\u001b', 'f').replace('\u001e', 'fl').replace('\u001f', 'fi')

target_csv = r'c:\Users\Alfredo Pabón\Documents\Proyectos antigravity\mundo_homeopatico_v2\carpeta_temporal_tablas\vademecum_maestro.csv'

with open(target_csv, 'a', encoding='utf-8', newline='') as f:
    f.write('\n' + csv_content.strip())

print('Bloque 9 (81-90) anexado correctamente.')
