import os

csv_content = """prod_101,PRODUCTOS MH,PLATA COLOIDAL( ARGENTUM MET D4 MH),25ppm de plata coloidal en agua destilada.,Antibiótico y antiséptico natural sin efectos secundarios. Se puede usar internamente o externamente; se muestra eficaz en el tratamiento de numerosas dolencias entre las que destacan las siguientes: acné; alergias; apendicitis; bursitis; tumores; verrugas; candidiasis; cistitis; cólera; colitis; infecciones; dermatitis; eccemas; diabetes; diarrea; disentería; erupciones; escarlatina; fatiga crónica; fibrosis; fiebre; forúnculos; gastritis; úlceras; blenorragia; gripe; heridas; herpes; lepra; lupus; malaria; meningitis; mononucleosis; neumonía; neurastenia; parásitos; pie de atleta; piorrea; pleuritis; problemas de tiroides; prostatitis; prurito; psoriasis; quemaduras; queratitis; resfriado; reumatismo; rinitis; seborrea; septicemia; sífilis; sinusitis; tiña; tos; toxemia; tuberculosis; gingivitis; úlceras varicosas.,USO INTERNO: 2 puff debajo de la lengua 3 veces al día; o una cucharada 3 veces al día. USO EXTERNO: Rociar sobre el área afectada las veces que sea necesario.,Frasco spray por 30 ml. Frasco x 100ml y x 240 ml.,activo
prod_102,PRODUCTOS MH,PLUMBUM D4 MH,Árnica montana D6; Carbo vegetabilis D30-D200; Causticum D6-D12-D30; Curarum D12-D30; Gelsemium D6-D12-D30; Kalium phos D12-D200; Magnesium phos D8-D12-D30; Nux vómica D12; Platinum met D12-D30; Plumbum iodatum D12-D30-D200; Rhus toxicodendron D6-D12-D30; Zincum val D12; D30; D200.,Parálisis generalizadas; atrofia muscular; parkinson; arteriosclerosis; rigidez articular; afecciones artríticas.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_103,PRODUCTOS MH,PULSATILLA D4 MH,Argentum Metallicum D3; Bórax D6; Candida D3; Echinacea angustifolia D12; Kreosotum D6; Pulsatilla D6.,Infecciones micóticas; tiña; micosis de los pies; pie de atleta; escamas blancas de la piel en manos o pies; candidiasis de garganta; dolor de oído con picor; decoloración blanca en las uñas; candidiasis vaginal u otra infección micótica de la piel.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_104,PRODUCTOS MH,RHAMNUS PURSHIANA D4 MH (Cáscara sagrada),Rhamnus purshiana(Cáscara sagrada) TM; D6 D12. Fel tauri TM; D6; D12.,Estreñimiento. Laxante suave. Antiparasitario.,,Frasco por 50 cápsulas.,activo
prod_105,PRODUCTOS MH,RHODODENDRON D4 MH,Berberis D4; Calcium phosphoricum D12; Causticum D6; Colocynthis D6; Dulcamara D4; Nux vómica D4; Plumbum D8; Rhododendron D4; Rhus Toxicodendron D4.,Lumbago; dolor lumbar en caso de alteraciones degenerativas reumáticas de la hernia discal.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_106,PRODUCTOS MH,RHUS TOX D4 MH (Cápsulas),Glycine max TM; Ascorbicum acidum D1; Boro D4; Glucosamine TM; Persea americana D1; Árnica D3-D6. Causticum D4-D6; Cuprum D8; Dulcamara D6; Formica Rufa D6-D12. Rhus Toxico-dendron D4-D6; Symphitum D4-D6. Vitamina D3 TM. Vitaminas E TM; y Zinc D4.,Artritis; artrosis de cadera y rodilla; desgaste del sistema locomotor; poliartrosis.,1 cápsula 3 veces al día,Frasco por 90 cápsulas,activo
prod_107,PRODUCTOS MH,RHUS TOX D4 MH,Ammonium carb. D3; Apis D6; Árnica D3-D6; Boro D4; Causticum D4-D6; Cuprum D8; Dulcamara D6; Formica Rufa D6-D12. Magnesia phos D6; Persea americana D3; Rhus Toxicodendron D4-D6; Symphitum D4-D6. Zinc D4.,Artritis; artrosis de cadera y rodilla; desgaste del sistema locomotor; poliartrosis.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_108,PRODUCTOS MH,RHUS TOX D4 MH CREMA,Árnica TM; D6-D12-D30-D200; Cannabis TM; D6-D12-D30-D200; Rhus tox D4.,Dolor agudo o crónico; dolor por enfermedades autoinmunes; traumatismos de partes blandas; fatiga muscular; dolor errático.,Aplicar 2 a 3 veces al día en el área afectada.,Tubo por 120gr.,activo
prod_109,PRODUCTOS MH,ROSMARINUS D4 MH LOCIÓN CAPILAR,Caléndula D3; Echinacea D3; Equisetum D3; Psorinum 30CH; Rosmarinus D4; Salvia D3; Selenio D4; Thallium D3; Graphites D4; Vitamina B6 (D6).,Alopecia; caspa; dermatitis; seborrea.,,Frasco Spray por 100 ml.,activo
prod_110,PRODUCTOS MH,ROSMARINUS D4 MH SHAMPOO,Shampoo sin sal; elaborado con extractos naturales de Caléndula; Rosmarunus; Salvia; Thallium; Vitaminas; entre otros.,Alopecia; caspa; dermatitis; seborrea; nutre y aporta brillo al cabello.,,Frasco Spray por 500 ml.,activo"""

# Limpieza de artefactos PDF
csv_content = csv_content.replace('\u001b', 'f').replace('\u001e', 'fl').replace('\u001f', 'fi')

target_csv = r'c:\Users\Alfredo Pabón\Documents\Proyectos antigravity\mundo_homeopatico_v2\carpeta_temporal_tablas\vademecum_maestro.csv'

with open(target_csv, 'a', encoding='utf-8', newline='') as f:
    f.write('\n' + csv_content.strip())

print('Bloque 11 (101-110) anexado correctamente.')
