import os

csv_content = """prod_071,PRODUCTOS MH,HYDRANGEA D4 MH,Berberis D3; Cantharis D6; Equisetum D6; Hydrangea D12; Pareira brava D3; Smilax D3; Sabal serrulata D6; Solidago D6; Uva ursi D4.,Litiasis renal; enuresis; depurativo renal; cistitis; depurativo sanguíneo; disfunciones prostáticas; diurético.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_072,PRODUCTOS MH,HYDRASTIS D4 MH,Hydrastis D4-D6-D12; Argentum nitricum D6; Euphorbium D4-D6; Hepar sulphur D8; Kali bich D8-D12; Luffa D6-D12; Phosphorus D6; Sulphur D200.,Hiposmia; anosmia; pólipos nasales; rinitis atrófica; rinitis aguda; sinusitis.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_073,PRODUCTOS MH,HYDROCOTYLE D4 MH CREMA,Hydrocotyle asiática D3 (centella asiática). Vitamina E natural; Vitamina A; Vitamina C; Salvia D3; Rosmarinus D3; Apis D3; Árnica D3; Caléndula D3; Sepia D3; Belladonna D3; Cutis D3; Graphites D3.,Antioxidante; prevención del cáncer de piel; dermatitis; cicatrizante.,,Gel 120g. Crema 120g,activo
prod_074,PRODUCTOS MH,HYPERICUM D4 MH,Ambra grisea D12-D30; Anacardium D12-D30; Gelsemium D30; Hyosciamus D30; Hypericum D30; Ignatia D12 D30; Litio D4; Valeriana officinalis D30.,Estados depresivos leves. Trastornos del sueño.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_075,PRODUCTOS MH,IGNATIA D4 MH,Avena sativa D6-D12; Gelsemium D6-D30-D200; Ignatia amara D6-D12; Kalium bromatum D8-D12; Melissa D3-D6-D12; Moschus D6-D30-D200; Passiflora D6; Phosphoricum acidum D6-D12; Sepia D8-D12; Valeriana D4-D6-D12; Zincum met D12.,Agotamiento físico y mental; tónico nervioso; estrés; insomnio; trastornos psiconerviosos.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_076,PRODUCTOS MH,IODUM D4 MH,Belladonna D30; Iodum D30; Juglans D6; Lapis albus D12; Lycopus virgin; D12; Natrium chlorat D30; Spongia D8; Galium aparine D6.,Tirotoxicosis; Morbus Basedow; hipertiroidismo; deficiencias cardíacas en caso de hipertiroidismo; bocio.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_077,PRODUCTOS MH,IPECA D4 MH,Ammonium carbonicum D8; Belladona D6; Bryonia alba D6; Corallium rubrum D8; Drosera D4; Ipeca D3; Kalium bichromicum D8; Natrum cloratum D6; Rumex crispus D4; Sambucus D3; Sanguinaria D6.,Asma; bronquitis; tos convulsiva; afonía. bronconeumonía; patologías respiratorias.,,Gotas x 30 ml; Tabletas x 90; Elixir x 240 ml (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_078,PRODUCTOS MH,IRIS D4 MH,Belladonna D6; Bryonia alba D6; Cedrón D6; Chamomilla D6; Actea racemosa D4; Gelsemium D3; Iris D4; Sanguinaria D4; Spigelia D4.,Cefaleas; migrañas; dolor de cabeza; neuralgias.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_079,PRODUCTOS MH,JABORANDI D4 MH,Jaborandi D4; Lachesis D30; Mezereum D12 D30; Nerium oleander D12 D30; Petroleum D6-D12; Silícea D30; Thuja D30.,Sudoración excesiva; mal olor por sudoración.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_080,PRODUCTOS MH,JUGLANS D4 MH,Allium sativum D6-D12; Antimonium crudum D12-D30; Apis D3-D6; Arsenicum album D6; Baptisia tinctoriana D3-D6; Baryta D8; Belladona D3-D6; Bryonia D6; Calcium Fluoricum D8; Cistus Canadensis D6; Echinacea D3-D6; D12; Equisetum D4; Fumaria D6; Galium D3-D6; Juglans D3-D6-D12; Phytolacca 4CH; Sarsaparrilla D3; D6; Scrophularia D3; Sulphur iodatum D8-D12-D30; Thuja D6; Urtica urens D3-D6.,Fortalece el sistema inmune; infecciones cutáneas; intoxicaciones digestivas; abscesos; supuraciones; inflamación de tejidos; linfatismo; depurador sanguíneo; depurador renal; pruritos; urticarias; inflamación de la pleura; inflamación glandular; adenopatías.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo"""

# Limpieza de artefactos PDF (de nuevo por si acaso)
csv_content = csv_content.replace('\u001b', 'f').replace('\u001e', 'fl').replace('\u001f', 'fi')

target_csv = r'c:\Users\Alfredo Pabón\Documents\Proyectos antigravity\mundo_homeopatico_v2\carpeta_temporal_tablas\vademecum_maestro.csv'

with open(target_csv, 'a', encoding='utf-8', newline='') as f:
    f.write('\n' + csv_content.strip())

print('Bloque 8 (71-80) anexado correctamente.')
