import os

csv_content = """prod_111,PRODUCTOS MH,ROSMARINUS D4 MH ACONDICIONADOR,Polycuaterno 7; Propylene Glycol; Glicerina; Aceite de Cacay; A2 Plus Liquid (es un eficiente sistema preservante de amplio espectro basado en preservativos cosméticos tradicionales y sin parabenos).,Acondicionador; desenredante y antiestático.,,Frasco Spray por 500 ml.,activo
prod_112,PRODUCTOS MH,RUMEX D4 MH,Chelidonium D3; Hepar sulphur D8-D30; Nux vómica D4; Rosmarinus D4; Rumex D6-D30; Juglans D3; Equisetum D4; Sarsaparrilla D6; Scrophularia D4; Thuja D6; Taraxacum D3; Berberis D4; Solidago D4.,Detoxificación completa a travez de cada sistema.^Drenaje linfático: Rumex; Juglans; Sarsaparrilla; Scrophularia y Thuja.^Drenaje hepático y biliar: Chelidonium; Hepar Sulphur y Rosmarinus.^Drenaje digestivo: Nux vómica y Taraxacum^Depurativo renal: Equisetum; Berberis y Solidago.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_113,PRODUCTOS MH,RUTA D4 MH,Aconitum napelus D6; Aesculus D6; Ambra grisea D8; Anacardium D8; Baryta D8; Cerebrum D8; China D6; Conium mac D6; Gelsemium D12; Hepar D8; Kalium phosp. D8; Passiflora D30-D200; Phosphoricum acid D6; Phosphorus D6; Ruta D6; Sepia D8.,Agotamiento; dificultades en el desarrollo mental de niños; dificultades intelectuales; trastornos de la función cerebral con disminución de la memoria; previene el envejecimiento prematuro.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Spray oral; Spray nasal; Viales nebulizables.,activo
prod_114,PRODUCTOS MH,RUTA ELÍXIR D4 MH Y RUTA VIAL BEBIBLE D4 MH,Ginseng D2; Cerebrum D3; Vit B2 D4; Vit B3 D4; Vit B6 D4; Vit B12 D4; Ginkgo biloba D2; Ruta D6.,Regenerador celular; dificultades en el desarrollo mental; trastornos de la función cerebral con disminución de la memoria; antienvejecimiento; bloqueador de radicales libres. Antioxidante; multivitamínico; regenerador orgánico; quelante oral; fortalece el sistema inmune.,,Elíxir por 240 ml. Caja por 12 viales bebibles de 10 ml.,activo
prod_115,PRODUCTOS MH,SABAL D4 MH,Apis D6; Árnica D6; Clematis erecta D8-D10; Chimaphila D3; Curcubita D4; Echinacea D4-D6; Hepar sulphur D10-D12; Lycopodium D12; Medorrinum D30-D100-D200; Pareira brava D10-D12; Prostata suis D8; Sabal serrulata D3-D6; Solidago D6; Thuja D6-D12.,Adenoma prostático; prostatitis; epididimitis; cistitis; hiperplasia prostática; inflamación de vías urinarias.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_116,PRODUCTOS MH,SALES DE SCHUSSLER D4 MH,Calcarea phosphorica D8; Calcarea fluorica D8; Calcarea sulfúrica D8; Ferrum phos D8; Kallium mur D8; Kallium phos D8; Kallium sul D8; Magnesia Phos D8; Natrum mur D8; Natrum sul D8; Natrum phos D8; Silícea D8.,Reposición de sales; personas convalecientes; estimula el crecimiento.,,Frasco por 90 tabletas o Triturado por 400g.,activo
prod_117,PRODUCTOS MH,SALVIA D4 MH CREMA O GEL,Hamamelis virginia D4; Anacardium D8; Salvia officinalis D4; Thymus vulgaris D4.,Tratamiento de todo tipo de acné; piel grasosa.,,Crema tubo por 120 g y Gel tubo de 120 g.,activo
prod_118,PRODUCTOS MH,SAMBUCUS ELÍXIR D4 MH,Aloe D3; Árnica montana D4; Atropha belladona D6; Carbo vegetabilis D12-D30; Chamomilla D3-D6; Drosera D3; Eucalipthus D3; Ferrum phosphoricum D8; Ignatia D4; Phosphorus D6; Pinus silvestris D6; Sambucus nigra D3-D6; Spongia officinalis D8.,Expectorante; sedante y depurador bronquial; broncodilatador.,,Elíxir por 240 ml.,activo
prod_119,PRODUCTOS MH,SCROPHULARIA D4 MH,China D12; Clematis erecta D6; Colchicum D9; Conium D12; Galium aparine D9; Hepar sulphur D9; Hydrastis D 12; Kreosotum D 12; Magnesium D4; Manganum D4; Naja tripudians D8; Psorinum D30; Pulsatilla D4; Scrophularia D6-D12; Sulphur iodatum D6; Thuja D4; Viscum album D9.,Coadyuvante en caso de tumores benignos y malignos; agrandamiento de las glándulas y alteraciones en la piel.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo
prod_120,PRODUCTOS MH,SELENIUM D4 MH,Arsenicum album C30-C200; Avena sativa C12 C30; Kali iodatum C12-C30; Phosphoricum acidum C12-C30-C200; Selenium C6-C12. Silícea C12-C30,Ansiedad.,,Gotas x 30 ml; Tabletas x 90 (En stock permanente) Bajo pedido: Glóbulos; Elixir; Spray oral; Spray nasal; Viales bebibles; Viales nebulizables.,activo"""

# Limpieza de artefactos PDF
csv_content = csv_content.replace('\u001b', 'f').replace('\u001e', 'fl').replace('\u001f', 'fi')

target_csv = r'c:\Users\Alfredo Pabón\Documents\Proyectos antigravity\mundo_homeopatico_v2\carpeta_temporal_tablas\vademecum_maestro.csv'

with open(target_csv, 'a', encoding='utf-8', newline='') as f:
    f.write('\n' + csv_content.strip())

print('Bloque 12 (111-120) anexado correctamente.')
